name: htto
channels:
  - astra-toolbox
  - conda-forge
  - savu-dep
dependencies:
  - astra-toolbox::astra-toolbox
  - conda-forge::click
  - conda-forge::cupy
  - conda-forge::h5py[build=mpi*]
  - conda-forge::mpi4py
  - conda-forge::numpy
  - conda-forge::nvtx
  - conda-forge::python
  - conda-forge::tomopy
  - savu-dep::larix
  - savu-dep::tomobar
